# **** make sure the first element can be found via pubchempy if a molecular weight is not given
identical_names = [
    (["H2O", "water", "deionized water", "deionized_water", "pure water", "ultra_pure water", "distilled water", "Deionized (DI) water", "Water"], 18.02),
    (["HAuCl4"], None),
    (["NaAuCl4", "sodium tetrachloroaurate (NaAuCl4)"], None),
    (["Tetrachloroauric acid trihydrate","HAuCl4·3H2O"], None),
    (["4-Hydroxy-TEMPO", "4-OH TEMPO", "4-OH-TEMPO"], None),
    (["Sodium tungstate dihydrate", "Na2WO4·2H2O"], None),
    (["Tetrabutylammonium bromide", "[(n-C4H9)4N]Br"], None),
    (["Cobalt chloride hexahydrate", "CoCl2·6H2O"], None),
    (["Sodium metasilicate", "Na2SiO3"], None),
    (["Oxalic Acid", "H2C2O4"], None),
    (["Copper(II) acetate", "Cu(CH3COO)2"], None),
    (["Antimony trioxide", "Sb2O3"], None),
    (["CaCl2", "calcium chloride solution"], None),
    (["(NH4)6Mo7O24.4H2O", "(NH4)6 Mo7O24 4H2O", "(NH4)6Mo7O24 4H2O"], None), 
    (["ethanol", "C2H5OH", "alchol", "Ethanol", "ETHANOL"], None), 
    (["Hydrazine sulfate", "N2H6SO4", "N2H6 SO4", "N2H4.H2SO4"], None), 
    (["Na2CO3", "sodium carbonate", "sodium carbonate solution"], None), 
    (["Na2MoO4.2H2O", "Na2MoO4 2H2O", "Na2MoO4·2H2O", "Sodium molybdate dihydrate"], None), 
    (["hydrochloric acid", "HCl", "hydrogen chloride"], None), 
    (["1,3,5-Tris(4-carboxyphenyl)benzene", "H3BTB"], None), 
    (["Iminodiacetic acid", "H2IDA"], None), 
    (["La(NO3)3.6H2O", "La(NO3)3 6H2O", "La(NO3)3·6H2O"], 433.01188), 
    (["Ni(NO3)2.6H2O", "Ni(NO3)2 6H2O", "Ni(NO3)2·6H2O"], 290.785),
    (["acetic acid","acetic acid solution"], None),
    (["HfOCl2.8H2O", "HfOCl2·8H2O", "HfOCl2 8H2O"], 409.52), 
    (["3,3-difluorocyclobutanamine hydrochloride", "[DF-CBA]Cl", "[DFCBA]Cl"], 143.56), 
    (["Bipyridine", "2,2′-bipyridine"], None),
    (["Manganese(II) acetate tetrahydrate","Mn(CH3COO)2·4H2O"], None), 
    (["CuCl2.2H2O", "CuCl2·2H2O", "copper(II) chloride dihydrate"], 170.48), 
    (["CuCl2", "copper(II) chloride"], None),
    (["FeCl3", "ferric chloride hexa-hydrate", "FeCl3.6H2O"], 162.2), 
    (["methanol", "absolute methanol", "CH3OH", "Methanol"], None), 
    (["NaBH4", "sodium boro-hydride"], None), 
    (["Ce(NH4)2(NO3)6", "Ce(NH4)2(NO3)6 solution"], 548.22), 
    (["Tetrabutylammonium chloride", "TBACl", "TBACl solution"], None), 
    (["H2SO4", "H2SO4 solution"], None), 
    (["cobalt acetate", "Co(OAc)2"], None), 
    (["Mn(CH3COO)2.4H2O", "Mn(CH3COO)2·4H2O"], None), 
    (["Na2WO4.2H2O", "Na2WO4·2H2O", "Na2WO4 solution", "Na₂WO₄ stock solution"], None), 
    (["ascorbic acid", "AA", "Ascorbic Acid"], None), 
    (["Gd(ClO4)3", "Gd(ClO4)3 stock solution", "Gd(ClO₄)₃ solution"], None), 
    (["sol.Mn", "sol.Mn stock solution"], 500), 
    (["Manganese(II) acetate", "Mn(CH₃COO)₂ stock solution"], None), 
    (["Sodium metasilicate", "Na2SiO3", "sodium silicate solution"], None), 
    (["H3BO3", "boric acid (H₃BO₃)", "H₃BO₃", "boric acid"], None), 
    (["HCOOH", "formic acid"], None), 
    (["ZrCl4", "ZrCl₄"], None), 
    (["CH3COOH", "acetic acid"], None), 
    (["DMF", "dimethylformamide"], None), 
    (["Cu(OAc)2.H2O", "Cu(OAc)2·H2O"], 199.65), 
    (["Na2HPO4.12H2O", "Na2HPO4·12H2O"], 358.14), 
]